version: '3.3'
services:
  api:
    container_name: api
    build:
      context:  .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
    links:
      - mongo
    depends_on:
      - mongo
    build:
      context: ./

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
    command:
      - mongod
  mongo-admin:
    image: mongo-express
    ports:
      - '8081:8081'
    links:
      - mongo
    depends_on:
      - mongo