version: '3.3'
services:
  api:
    container_name: api
    build:
      context:  .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8082
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8082:8082'
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - mychatnetwork


  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
    command:
      - mongod
    networks:
      - mychatnetwork

  mongo-admin:
    image: mongo-express
    ports:
      - '8081:8081'
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mychatnetwork
  
  
  
  rabbitmq:
    image: rabbitmq:3.8.11-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mychatnetwork



networks:
  mychatnetwork:
    driver: bridge